### ISSUE TITLE
[Suggestion] Meat

### ISSUE THREAD

**Issue by OhHeyItsK** [SaltSouls/Packed-Up#13]
Having storage for beef, pork, chicken, mutton, fish, and rabbit would be great for all those large-scale modded farms. Mob drops in general would be nice eventually, but I'm specifically addressing meat because I've seen sack/crate mods for hostile mob drops, but never any for passive ones besides eggs and feathers.

**Comment by SaltSouls** [comment]
I would suggest you look into the texture files. What you find might surprise you.

**Comment by OhHeyItsK** [comment]
My excitement has intensified haha. Looking forward to future updates. Also looking forward to seeing how some of these smaller textures like the sand bucket and tiny piles of things are gonna be implimented.
