### ISSUE TITLE
[CRITICAL BUG] Startup Crash with Supplementaries 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by CraftyZombie** [SaltSouls/Packed-Up#15]
**Describe the Bug:**
The game crashes on startup. This is due to the strict load order that Packed Up demands, but it's unclear why it needs it. 
<img width="607" alt="Screen Shot 2024-11-02 at 11 59 12 AM" src="https://github.com/user-attachments/assets/e81a64a1-6221-4209-b4d1-2be3aa12338e">

**To Reproduce:**
Start the game with Packed Up and Supplementaries.

**Expected Behavior:**
The game loads.

**Version (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.3.11
 - Mod Versions: 
<img width="302" alt="Screen Shot 2024-11-02 at 12 00 33 PM" src="https://github.com/user-attachments/assets/e1ecd69e-dc3a-48bb-a43d-f88749628bf8">

**Log Files:**
(https://gist.github.com/CraftyZombie/3e41a4635c29e6aa3f72c4955a54d558)

**Additional Context**
Discord Thread: https://discord.com/channels/790151253144895508/1302311136623988747

**Comment by SaltSouls** [comment]
Hmmm... I'll take a look into this. Sounds like it should be an easy enough fix.

**Comment by CraftyZombie** [comment]
Thank you.

**Comment by CraftyZombie** [comment]
![image](https://github.com/user-attachments/assets/ab651838-b507-4045-9aac-dcf051842c7a)
Should specify the issue is here.

**Comment by SaltSouls** [comment]
Yes. Seems like it can be fixed by just changing the ordering for FD to none.

**Comment by SaltSouls** [comment]
Fixed in [4e80ae2](https://github.com/SaltSouls/Packed-Up/commit/4e80ae262d0b095628bebb8c12b7b57d2ebbe4d9)
