### ISSUE TITLE
Placing a crate lid under a crate

### ISSUE THREAD

**Issue by ziad25139** [SaltSouls/Packed-Up#16]
**Describe the Bug:**
u can basically crash ur mc if u place a crate lid under a crate

**To Reproduce:**
1. Place a crate
2. Make space under the crate
3. Look at the bottom of the crate
4. Place crate lid
5. Get error about direction (DirectionProperty) that doesnt support down (allowed directions: [north, south, west, east])

**Expected Behavior:**
it just doesn't place

**Version (please complete the following information):**
 - Minecraft: 1.20.1 (Singleplayer)
 - Forge: 47.3.12
 - Mod: 0.5.3

**Logs:** https://mclo.gs/pltLEiw

**Comment by SaltSouls** [comment]
Just saw this. Already fixed the issue, and will post the fix as soon as I fix a separate issue I'm having.
